language: java

jdk:
  - openjdk13

notifications:
  email: false

before_install:
 - chmod +x gradlew

script:
  - ./gradlew check # Run testen
  - cd ./src/main/java
  - javac Calculator.java # Compile
  - java -cp Calculator 1 4 # Run
