language: java

jdk:
  - openjdk13

notifications:
  email: false

install:
  - ./gradlew check # Run testen
  - cd ./src/main/java
  - javac Calculator.java # Compile
  - java -cp Calculator 1 4 # Run
