language: java

jdk:
  - openjdk13

env:
#  - NODE_VERSION="12.10.0"
  - CALCULATOR_PATH="./src/main/java"

notifications:
  email: false

before_install:
  - ./gradlew assemble

install:
  - ./gradlew test # Run testen
  - cd $CALCULATOR_PATH
  - javac Calculator.java # Compile
  - java -cp Calculator 1 4 # Run
