language: java

jdk:
  - openjdk13

notifications:
  email: false

before_install:
 - chmod +x gradlew

script:
  - ./gradlew check # Run testen
  - javac ./src/main/java/Calculator.java # Compile
  - java -cp ./src/main/java/ Calculator 1 4 # Run
